import { NextRequest, NextResponse } from 'next/server';
import { assertSameOrigin } from '@/lib/auth';
import { getDatabase } from '@/lib/db';
import { requirePermission } from '@/lib/rbac';
import { apiError, parseJson } from '@/lib/security';
import { z } from 'zod';
const schema = z.object({ id: z.number().int().positive().optional(), slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).min(3).max(180), title: z.string().min(5).max(180), excerpt: z.string().max(500).default(''), body: z.string().min(20).max(50000), category: z.string().min(2).max(80).default('How to repair'), coverImageUrl: z.string().url().or(z.literal('')).default(''), status: z.enum(['draft', 'published', 'archived']).default('draft') });
export async function GET(request: NextRequest) { try { await requirePermission(request, 'content.manage'); const database = getDatabase(); const posts = await database`SELECT id, slug, title, excerpt, body, category, cover_image_url, status, author_id, published_at, created_at, updated_at FROM blog_posts ORDER BY updated_at DESC LIMIT 200`; return NextResponse.json({ posts }); } catch (error) { return apiError(error); } }
export async function POST(request: NextRequest) { try { assertSameOrigin(request); const actor = await requirePermission(request, 'content.manage'); const payload = await parseJson(request, schema); const database = getDatabase(); const publishedAt = payload.status === 'published' ? new Date().toISOString() : null; const rows = await database`INSERT INTO blog_posts (slug, title, excerpt, body, category, cover_image_url, status, author_id, published_at, updated_at) VALUES (${payload.slug}, ${payload.title}, ${payload.excerpt}, ${payload.body}, ${payload.category}, ${payload.coverImageUrl}, ${payload.status}, ${actor.id}, ${publishedAt}, NOW()) RETURNING id, slug`; await database`INSERT INTO admin_activity (actor_id, activity_type, details) VALUES (${actor.id}, 'blog_post_created', ${JSON.stringify({ postId: rows[0].id, status: payload.status })}::jsonb)`; return NextResponse.json({ post: rows[0] }, { status: 201 }); } catch (error) { return apiError(error); } }
export async function PUT(request: NextRequest) { try { assertSameOrigin(request); const actor = await requirePermission(request, 'content.manage'); const payload = await parseJson(request, schema.extend({ id: z.number().int().positive() })); const database = getDatabase(); const publishedAt = payload.status === 'published' ? new Date().toISOString() : null; const rows = await database`UPDATE blog_posts SET slug = ${payload.slug}, title = ${payload.title}, excerpt = ${payload.excerpt}, body = ${payload.body}, category = ${payload.category}, cover_image_url = ${payload.coverImageUrl}, status = ${payload.status}, published_at = ${publishedAt}, updated_at = NOW() WHERE id = ${payload.id} RETURNING id, slug`; if (!rows.length) return NextResponse.json({ error: 'Article not found' }, { status: 404 }); await database`INSERT INTO admin_activity (actor_id, activity_type, details) VALUES (${actor.id}, 'blog_post_updated', ${JSON.stringify({ postId: payload.id, status: payload.status })}::jsonb)`; return NextResponse.json({ post: rows[0] }); } catch (error) { return apiError(error); } }
