'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Search, ShieldCheck, Users } from 'lucide-react';

type User = { id: number; email: string; name?: string | null; username?: string | null; country?: string | null; role: 'admin' | 'moderator' | 'editor' | 'support' | 'member'; account_status: 'active' | 'suspended' | 'pending'; is_admin?: boolean; subscription_plan?: string | null; subscription_expires_at?: string | null; created_at: string };
const roleLabels = { admin: 'Administrator', moderator: 'Moderator', editor: 'Resource editor', support: 'Support agent', member: 'Member' };

export default function AdminUsersPage() {
  const router = useRouter();
  const [users, setUsers] = useState<User[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [saving, setSaving] = useState<number | null>(null);
  async function loadUsers(query = '') { setError(''); const response = await fetch(`/api/admin/users?search=${encodeURIComponent(query)}`, { cache: 'no-store' }); if (response.status === 401 || response.status === 403) { router.push('/login'); return; } if (!response.ok) throw new Error('Members could not be loaded.'); const data = await response.json(); setUsers(data.users || []); }
  useEffect(() => { loadUsers().catch((cause) => setError(cause instanceof Error ? cause.message : 'Members could not be loaded.')).finally(() => setLoading(false)); }, []);
  async function saveUser(user: User) { setSaving(user.id); setError(''); try { const response = await fetch('/api/admin/users', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: user.id, role: user.role, accountStatus: user.account_status }) }); if (!response.ok) throw new Error((await response.json()).error || 'Could not save this user.'); await loadUsers(search); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not save this user.'); } finally { setSaving(null); } }
  function patch(id: number, change: Partial<User>) { setUsers((current) => current.map((user) => user.id === id ? { ...user, ...change } : user)); }
  return <div className="admin-page page-shell"><Link href="/admin" className="admin-back"><ArrowLeft size={15} /> Admin dashboard</Link><div className="admin-page__top"><span className="eyebrow"><Users size={14} /> Access control</span><h1>Users and roles</h1><p>Search accounts, assign the least access they need, and suspend accounts without deleting their history.</p></div>{error && <div className="form-error" role="alert">{error}</div>}<section className="admin-section"><div className="admin-users-toolbar"><label className="admin-search"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by email, name, or username" onKeyDown={(event) => { if (event.key === 'Enter') loadUsers(search).catch((cause) => setError(cause instanceof Error ? cause.message : 'Search failed.')); }} /></label><button className="button button--secondary" type="button" onClick={() => loadUsers(search)}>Search</button></div>{loading ? <div className="membership-status">Loading members…</div> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Member</th><th>Role</th><th>Account status</th><th>Membership</th><th>Save</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong>{user.name || user.username || 'Unnamed member'}</strong><small>{user.email}{user.country ? ` · ${user.country}` : ''}</small></td><td><select className="form-control" value={user.role || (user.is_admin ? 'admin' : 'member')} onChange={(event) => patch(user.id, { role: event.target.value as User['role'] })}>{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></td><td><select className="form-control" value={user.account_status || 'active'} onChange={(event) => patch(user.id, { account_status: event.target.value as User['account_status'] })}><option value="active">Active</option><option value="suspended">Suspended</option><option value="pending">Pending</option></select></td><td>{user.subscription_plan ? <><strong>{user.subscription_plan}</strong><small>{user.subscription_expires_at ? `Until ${new Date(user.subscription_expires_at).toLocaleDateString()}` : 'No expiry'}</small></> : 'Free access'}</td><td><button className="button button--small button--primary" type="button" onClick={() => saveUser(user)} disabled={saving === user.id}>{saving === user.id ? 'Saving…' : 'Save'} {user.role === 'admin' && <ShieldCheck size={13} />}</button></td></tr>)}</tbody></table>{!users.length && <p className="admin-empty">No matching accounts were found.</p>}</div>}</section></div>;
}
